# Generated by Django 4.2.1 on 2023-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0004_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='booked', max_length=20, null=True),
        ),
    ]
