# Generated by Django 4.2.1 on 2023-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
